# Generated by Django 3.2.9 on 2022-01-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('primarytype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.type')),
            ],
        ),
    ]
